---
##############################
# How made by DJKaiMc
# Twitter: @DJKaiMc
# How: Tell you players how to play!
##############################


#Add instructions below, You can use Minecraft Volour codes!
how1: "§bHow to play: §eMine blocks, place blocks, Fight and win!"
...